version: '3.5'
services:
  database:
    image: mysql
    ports:
      - "3306:3036"
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: node-express
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
